SystemOrganization addCategory: #'SmallKanren-Core'!
SystemOrganization addCategory: #'SmallKanren-Core-Constraints'!
SystemOrganization addCategory: #'SmallKanren-Core-Debugging'!
SystemOrganization addCategory: #'SmallKanren-Core-Goals'!
SystemOrganization addCategory: #'SmallKanren-Core-Heuristics'!
SystemOrganization addCategory: #'SmallKanren-Core-Running'!
SystemOrganization addCategory: #'SmallKanren-Core-Variables'!
