SystemOrganization addCategory: #'SmallKanren-Core'!
SystemOrganization addCategory: 'SmallKanren-Core-Constraints'!
SystemOrganization addCategory: 'SmallKanren-Core-Debugging'!
SystemOrganization addCategory: 'SmallKanren-Core-Delayed'!
SystemOrganization addCategory: 'SmallKanren-Core-Goals'!
SystemOrganization addCategory: 'SmallKanren-Core-Streams'!
SystemOrganization addCategory: 'SmallKanren-Core-Tabling'!
SystemOrganization addCategory: 'SmallKanren-Core-Variables'!
